# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-09 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nike_name', models.TextField()),
                ('avatar_url', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('gender', models.TextField(null=True)),
            ],
            options={
                'db_table': 'msys_user',
            },
        ),
    ]
