# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-10 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20180609_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('reg_id', models.BigIntegerField(default=0, max_length=20, primary_key=True, serialize=False)),
                ('phone', models.CharField(default='', max_length=64)),
                ('code', models.CharField(default='', max_length=32)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
