# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='cinema',
            fields=[
                ('cin_id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=64, null=True)),
                ('jobtime', models.TextField(null=True)),
            ],
            options={
                'db_table': 'cinema',
            },
        ),
        migrations.CreateModel(
            name='cinema_comment',
            fields=[
                ('com_id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('cin_id', models.BigIntegerField(max_length=20)),
                ('user_id', models.BigIntegerField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'cinema_comment',
            },
        ),
        migrations.CreateModel(
            name='mov_peo',
            fields=[
                ('mov_peo_id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('mov_id', models.BigIntegerField(max_length=20)),
                ('peo_id', models.BigIntegerField(max_length=20)),
                ('flag', models.IntegerField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'mov_peo',
            },
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('movie_id', models.BigIntegerField(default=0, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('grade', models.FloatField(default=0.0)),
                ('starttime', models.DateTimeField()),
                ('type', models.TextField(null=True)),
                ('region', models.TextField(null=True)),
                ('language', models.CharField(default='', max_length=32)),
                ('length', models.IntegerField(default=0)),
                ('imgUrl', models.TextField(null=True)),
                ('prevueUrl', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='people',
            fields=[
                ('peo_id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('gender', models.IntegerField(max_length=1)),
                ('job', models.TextField(null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('seat_id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('vh_id', models.BigIntegerField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('row_col', models.CharField(max_length=64)),
                ('user_id', models.BigIntegerField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('tkt_id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(max_length=20)),
                ('vh_mov_id', models.BigIntegerField(max_length=20)),
                ('seat_id', models.BigIntegerField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.BigIntegerField(default=0, max_length=20, primary_key=True, serialize=False)),
                ('phone', models.CharField(default='', max_length=64)),
                ('password', models.CharField(default='', max_length=32)),
                ('name', models.CharField(max_length=128, null=True)),
                ('pay_num', models.CharField(max_length=64, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='video_hell',
            fields=[
                ('vh_id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('cin_id', models.BigIntegerField(max_length=20)),
                ('name', models.CharField(max_length=128, null=True)),
                ('number', models.CharField(max_length=20)),
                ('screen_size', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'video_hell',
            },
        ),
        migrations.CreateModel(
            name='video_movie',
            fields=[
                ('vh_mov_id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('vh_id', models.BigIntegerField(max_length=20)),
                ('mov_id', models.BigIntegerField(max_length=20)),
                ('type', models.CharField(max_length=2, null=True)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('price', models.BigIntegerField(max_length=20)),
            ],
            options={
                'db_table': 'video_movie',
            },
        ),
    ]
